### ISSUE TITLE
meta bug: lift required arguments into the clang driver

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#812]
There are a handful of arguments that must be passed to Clang to compile for Android that ought to be handled by Clang itself. This bug tracks enumerating those and tracking the individual bugs for each.

Required, your code will not work without these (at least in some situations):

- [x] `-stdlib=libc++` https://reviews.llvm.org/D53109 r346167
- [X] `-mfpu=vfpv3-d16` https://reviews.llvm.org/D53121 r344367
- [X] ~`-Wl,--fix-cortex-a8`~ (insignificant number of devices with Cortex-A8 CPUs, flag is no longer used)
- [X] ~`-Wl,-z,nocopyreloc`~ (no longer needed because PIE makes copy relocations unnecessary)
- [X] `-Wl,-z,relro` https://reviews.llvm.org/D53117 r344295

Technically required, but will not result in an error if not used because the linker assumes it to be true:

- [X] `-Wl,-z,now` https://reviews.llvm.org/D53117 r344295

And finally,

- [X] Update Clang to pull in the above patches.

Moved to r21:

- `-Wl,--warn-shared-textrel` https://reviews.llvm.org/D53344
- `-Wa,--noexecstack` https://reviews.llvm.org/D53343
- `-Wl,-z,noexecstack` https://reviews.llvm.org/D53343
- `-fstack-protector-strong`

**Comment by pirama-arumuga-nainar** [comment]
Note that during LTO, assembly happens during linking; `-Wa,--no-exec-stack` should be passed to the linker plugin as well.

**Comment by DanAlbert** [comment]
I *think* that should be handled by the change I uploaded to lift this into the driver, but should definitely check.

**Comment by pirama-arumuga-nainar** [comment]
Aah, sorry I brought it up here.  LTO + `-Wa,--no-exec-stack` is currently broken and needs to be fixed - the `-mnoexecstack` doesn't get passed to the backend because LTO creates a new backend during linking.  That's orthogonal to what you're doing here.  I'll file an internal bug :)
