### ISSUE TITLE
r21 Clang driver improvements meta bug

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#944]
Tracking bug for the Clang driver improvements that will be made for r21 (carry over from https://github.com/android-ndk/ndk/issues/812).

- [x] `-Wl,--warn-shared-textrel` https://reviews.llvm.org/D53344 r357296
- [x] `-Wa,--noexecstack` https://reviews.llvm.org/D53343 r357197
- [x] `-Wl,-z,noexecstack` https://reviews.llvm.org/D53343 r357197
- [x] `-mfpu=neon` https://reviews.llvm.org/D58153 r354166 (https://github.com/android-ndk/ndk/issues/859)

Recommended, improves security (may not lift into the driver, but will document for users):

- `-fstack-protector-strong`

And finally,

- [x] Update Clang to pull in the above patches.

**Comment by DanAlbert** [comment]
The above patches are now in the NDK in master. https://android-review.googlesource.com/c/platform/ndk/+/1114053 cleans up our build systems to stop passing the redundant flags. `-fstack-protector-strong` should still be added to the docs.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/1114055 documents `-fstack-protector-strong`.
